### ISSUE TITLE
Publishing plugin is broken

### ISSUE THREAD

**Issue by komu** [EvidentSolutions/gradle-beanstalk-plugin#14]
For some reason `./gradlew clean publishPlugins` is broken on Gradle plugin repository. It seems like the plugin gets published, but one can't actually use the published bits.

**Comment by musketyr** [comment]
still the same :-/ even `0.2.2+2` doesn't seem visible. do I have to add some another repository to the build file?

**Comment by komu** [comment]
For a while I though that perhaps the fact that I upgraded Gradle from 2.3 to 4.2 (57005f6f7a2f8) somehow broke publishing. But I tried downgrading back to 2.3 and published `0.1.2+3` with it and got same results...

Perhaps the plugin repository does not support the old version of `com.gradle.plugin-publish` anymore. I'll try updating that.

**Comment by komu** [comment]
Yeah, upgrading `com.gradle.plugin-publish` from `0.9.1` to `0.9.9` did the trick.

I released `0.1.3` which should now work.

**Comment by musketyr** [comment]
LGTM
