### ISSUE TITLE
Can I use ebextensions?

### ISSUE THREAD

**Issue by boryaku** [EvidentSolutions/gradle-beanstalk-plugin#15]
Hi can I use the .ebextensions with the plugin?  What I'm looking to do is land a application.properties file in my EC2 instance that is loaded from S3.

It would be really handy if I could use the deployments closure to specify a file to upload.  Not really sure the best approach and I don't know if .ebextensions would be able to help me deploy a application.properties file dependent on the environment.?.

thanks,

chris

**Comment by komu** [comment]
Hi,

I've never tried using `.ebextensions` so I'm not sure what it would involve.

Anyway, haven't used Beanstalk at all in a while, so I the plugin has certainly stagnated.
