### ISSUE TITLE
Deploy fails when S3 bucket is in different region than beanstalk application

### ISSUE THREAD

**Issue by tylervz** [EvidentSolutions/gradle-beanstalk-plugin#18]
I am using version 0.2.0 of this plugin, and have successfully used this plugin with a different project.

I created an Elastic Beanstalk application in us-east-1 and somehow its corresponding S3 bucket is in us-east-2. The URL for my beanstalk environment is `<application>.us-east-1.elasticbeanstalk.com`, but the S3 bucket that contains the .war files of all the application versions is a us-east-2 bucket.

When I set both endpoints to us-east-1
```
s3Endpoint = "s3-us-east-1.amazonaws.com"
beanstalkEndpoint = "elasticbeanstalk.us-east-1.amazonaws.com"
```
then I get the following error when deploying:
```
Unknown host 'elasticbeanstalk-us-east-1-<account_number>.s3-us-east-1.amazonaws.com'.
```

When I change the `s3Endpoint` to `"s3-us-east-2.amazonaws.com"` then I get this error:
`> The bucket is in this region: null. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: F97F0BEE4EAC05C7)`

**Comment by komu** [comment]
Thanks for the report!

I'm afraid that I don't have time to look into this: I haven't used BeanStalk personally in a couple of years so I've just been merging PRs created by others.

Anyway, it sounds weird that the bucket is in another region. Perhaps you could try rebuilding the instance?
