### ISSUE TITLE
AWS instance profile is not used by plugin 

### ISSUE THREAD

**Issue by bartosz-bilicki** [EvidentSolutions/gradle-beanstalk-plugin#21]
My plugin run is failing (on jenkins instance) because
`Unable to load AWS credentials from any provider in the chain`

Checking source code (`DeployTask.deploy`) I see that `AWSCredentialsProviderChain `misses
`com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper` (comparing to `com.amazonaws.auth.DefaultAWSCredentialsProviderChain`).

Is there a reason for not including `EC2ContainerCredentialsProviderWrapper  `(or `com.amazonaws.auth.InstanceProfileCredentialsProvider`) as last element of the chain?

I have no profile configured on my jenkins EC2 machine- it contains just instance profile.
Without `InstanceProfileCredentialsProvider `in the chain, I cannot use plugin from jenkins.

**Comment by komu** [comment]
I think it's just an oversight. I haven't used BeanStalk for quite a while, but if you can make.a PR, I'll merge and make a new release.

**Comment by bartosz-bilicki** [comment]
thanks for merging my PR!
could you please also make new release of the plugin (v0.2.1)  to gradle plugin repository?

**Comment by komu** [comment]
I thought I did when I made the release. Here it is: https://plugins.gradle.org/plugin/fi.evident.beanstalk

Are there some problems with the bits?

**Comment by bartosz-bilicki** [comment]
> I thought I did when I made the release. Here it is: https://plugins.gradle.org/plugin/fi.evident.beanstalk
> 
> Are there some problems with the bits?

It works just fine. My problem is solved (instance profile is used). I just missed updated version on https://plugins.gradle.org/plugin/fi.evident.beanstalk  (I was checking only github releases https://github.com/EvidentSolutions/gradle-beanstalk-plugin/releases)

**Comment by komu** [comment]
Great!

I just updated the changelog and forgot that I've previously updated GitHub release notes as well on this project. I'll do that as well.

**Comment by komu** [comment]
Oh, I forgot to push while releasing. That's embarrassing. 😆
