### ISSUE TITLE
Java modular system error

### ISSUE THREAD

**Issue by eloyleonardo** [EvidentSolutions/gradle-beanstalk-plugin#23]
Java 9 made some changes on default modules, in newest java it was removed from the class path. How can I use the plugin in newest java version ? 
Running like documentation it gives an NoClassDefFoundError on javax/xml/bind/DatatypeConverter.

There is any way to use in newest version ?
Thank you

**Comment by komu** [comment]
Right. The problem could be worked around by adding JAXB dependencies manually to the plugin, but perhaps the latest [AWS SDK for Java](https://github.com/aws/aws-sdk-java) has already fixed this on their side? We seem to be at version `1.11.32`:

https://github.com/EvidentSolutions/gradle-beanstalk-plugin/blob/fd256c9c13a4963a09f6f2961fdba5589a6f24b3/build.gradle#L12

whereas the latest version of AWS SDK is `1.11.527`. It could be worth a try to just bump the AWS API version and check if it fixes the problem. If that doesn't help, then I guess we'll just need to add the required dependencies manually.

Unfortunately I haven't used AWS myself for a while and don't even have a test EBS-instance at the moment, so I can't really make any promises about working on this issue. But if you or someone else makes a PR and tests it, I'd be happy to make a new release.

**Comment by eloyleonardo** [comment]
First of all thank you for your answer.

For now I migrate to java 10 so even as deprecated I can still use the Jaxb dependencies.

About the changes, witch is the best way to test ?
Publish to a local maven with the new version and change my project to use the new version?

**Comment by komu** [comment]
Yes, publishing to local repository should work. If you are currently using the `plugins { ... }` -syntax, you'll need to change that to `buildscript { ... }` and use `apply` to apply the plugin. [This blog post](https://shekhargulati.com/2015/09/10/gradle-tip-using-gradle-plugin-from-local-maven-repository/) provides the details.
