### ISSUE TITLE
S3 Uploads can override pre-existing ones (different version) causing deploy inconsitancies 

### ISSUE THREAD

**Issue by vicsz** [EvidentSolutions/gradle-beanstalk-plugin#8]
S3 Uploads are key'ed on war name.  This has the potential to cause inconsistencies during deployments if war files names aren't uniquely identified per version.  

Steps to replicate:

Build and deploy a version to Beanstalk using the plugin.   Call this Version 1
- note that the plugin will create a new S3 key value pair , keyed on application-name.war

Modify some code, build + deploy to beanstalk using the plugin.  Call this Version 2 ( at this step don't change the war name of the build artifact , i.e. version information if applicable). 
- plugin will deploy to S3 .. but it will override the previous upload due to the same key name
- Version 1 application file (from Beanstalk) will now point to this version of the file

Promote Version 1 to another environment (or even redeploy) 
- note that it will deploy Version 2. 

Suggestions:
- at a random hash to the key information @ S3 to prevent duplicates. 

Issue is in the following code:

 String bucketName = elasticBeanstalk.createStorageLocation().getS3Bucket();
        String key = urlEncode(warFile.getName());

        s3.putObject(bucketName, key, warFile)

**Comment by komu** [comment]
I just released `0.1.0` with this fix.
